### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by muntakimrafi** [UBC-MDS/dropout-predictions#56]
I Could not create the anaconda environment using the provided .yml file. Please fix your .yml file as soon as possible so that I can check your code.

**Comment by caesarw0** [comment]
Hi @muntakimrafi , thanks for your comment, we have changed the .yml file, and it should be fine to create the environment. Let us know if there is any issue with the .yml file. Thanks!

https://github.com/UBC-MDS/dropout-predictions/blob/main/env/dropout_pred_env.yml

**Comment by muntakimrafi** [comment]
Congratulations on finishing milestone 2! 

- [ ] Initially the environemnt was set up incorrectly. -5
- [ ]  Analysis code is satisfactory.
- [ ]  Version controlling was satisfactory.
- [ ]  I ran the code and recreated the analysis in the results directory. However, I was not able to create the final analysis report. Libraries required to run       
`Rscript -e 'rmarkdown::render("../doc/The_Report_of_Dropout_Prediction.Rmd")'
`
was not included in the environment file. -5
- [ ] Submission expectations were met.

**Comment by caesarw0** [comment]
Thanks for TA's comment, the environment and R dependencies are fixed starting from milestone 3. Thanks!

https://github.com/UBC-MDS/dropout-predictions/commit/da2a00c14422ecd6520a8c1a9a0139a3963f94fb
