### ISSUE TITLE
Milestone 4 - Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/dropout-predictions#79]
**Congratulations on finishing milestone 4!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.

## Dependency diagram of the Makefile (max 5 points)
Good Job!
### Dockerfile

- [ ] The base image the `Dockerfile` uses in the `FROM` statement should have it's version pinned. 
Failing to do this, means that each time the Docker image is built in the future, 
the latest version of the base image will be used.
The latest version of the base image will very likely change over time, 
and failing to do this will lead to the container not being able to be reproducibly built in the future. **-2 quality**
- [ ] The dependencie versions are not pinned. -2 quality
**Comment: Missing tag for "jupyter/scipy-notebook" and missing version number for several dependancies including r-knitr and r-kableextra**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
If a specific value needs to be inserted (e.g., volume mounting, port forwarding, tag version - which should be specified, as relying on `latest` is unreliable for many reasons, etc) 
suggest the most reasonable value and provide the list 
(or link to a list) of alternative options. **-2 mechanics**
**Comment: Specify the tag for pulling docker file rather than using latest**

## Final Submission: Improve the project based on the feedback received
Good Job!
### Expectations
Good Job!
